### PR TITLE
Add MAX78002 SoC files into Zephyr system

### PR DESCRIPTION
**Pull request by hfakkiz**
This PR adds MAX78002 SoC files into the Zephyr system to enable Zephyr support for this SoC. Also, it includes some updates (which already merged to MSDK repository) for bare-metal drivers.

**MSDK PRs:**
- https://github.com/analogdevicesinc/msdk/pull/1170
- https://github.com/analogdevicesinc/msdk/pull/1142
- https://github.com/analogdevicesinc/msdk/pull/1235
- https://github.com/analogdevicesinc/msdk/pull/1158

### CODE REVIEW

**Comment by hfakkiz** [comment]
@MaureenHelm FYI.

**Comment by MaureenHelm** [comment]
Can you provide links to the MSDK PRs please?

**Comment by hfakkiz** [comment]
> Can you provide links to the MSDK PRs please?

Updated PR message with MSDK PR links

**Comment by hfakkiz** [comment]
[MAX78002](https://github.com/zephyrproject-rtos/zephyr/pull/80247) PR passed all twister tests. If it is okay for you, please merge this PR. @MaureenHelm

**Review by MaureenHelm — APPROVED** [review]

**Pull request merged**
